project:
  type: website

website:
  title: "STAT390 project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - step1.qmd
      - step2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: source

