project:
  type: website

website:
  title: "Fall 2024 STAT390 project"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - about.qmd
      - step1.qmd
      - step2.qmd
      - step3.qmd
      - step4.qmd
      - litreview.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: source

