project:
  type: website

website:
  title: "2025 STAT390 C-MIL project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - step1.qmd
      - step2.qmd
      - step3.qmd
      - step4.qmd
      - step5_previous_approach.qmd
      - step5_models.qmd
      - litreview.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: source

