---
title: "About"
---

This is the website for the STAT390 C-MIL Classification project!


## People

**Project Co-ordinator**: Arvind Krishna

**Team Members**:

- Thinkers: John Olsen, Kota Suzuki, Yaelle Pierre, Jake Mead, Ryan Yi,	Anna Roney
- Coders: Sari Eisen, Sharon Lin,	Ryan Lach,	Nathan Jung,	Hannah Ma
- Literature Surveyors: William Wang,	Bennett Markinson,	Allen Zhang,	Alex Zhou,	Jacob Muriel,	Patrick Schmid,	Lainey Neild
- Consultants/Organizers/Testers: Olivia Joung,	Anna Deka,	Margaret Pirozzolo,	Jack Ouyang,	Haneef Usmani,	Radhika Todi
- Health Informaticians: Lucinda Hu,	Dila Bitlis,	Julia Nelson,	Walker Frisbie,	Kayla Terrelonge

**Stakeholders**: Dr. Yamini Krishna, Dr. He Zhao, Prashant Kumar

## GitHub and OneDrive

This **[GitHub](https://github.com/arvindkrishna87/STAT390_WI2025.git)** contains all the necessary code and algorithms from our progress:



This **[OneDrive](https://nuwildcat-my.sharepoint.com/personal/akl0407_ads_northwestern_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fakl0407%5Fads%5Fnorthwestern%5Fedu%2FDocuments%2FSTAT390&sortField=LinkFilename&isAscending=true)** contains all data and processed folders from our progress:



## Data Overview

The [Data](https://www.sciencedirect.com/science/article/pii/S0023683723002246) consists of 105 cases from 97 patients. Below are some statistics of the data:

- 60 women (age range: 23-93 years; median 65; mean 61.5) and 37 men (age range:
31-91 years; median 68; mean 66.5)

- The ethnic group mix comprised of the following: 88 White Caucasian, 4 Black, 2
South Asian, 1 Inuit, 1 Mixed race, and 1 Unspecified

The data corresponds to patients in the following 3 ocular oncology/pathology
centers:

- Liverpool University Hospitals NHS Foundation Trust (**Liverpool**; cases from
2018 to 2021),
- Royal Hallamshire Hospital (**Sheffield**; from 2011 to 2021), and
- Rigshospitalet (**Copenhagen**; from 1996 to 2021)


For each patient, a tissue is taken from their conjunctiva. The tissue is sliced into multiple slices. Multiple slices are used so that each slice can be analyzed separately and there is more evidence to support the conclusion,
i.e., the classification of the C-MIL.
