---
title: "Step 2: Matching slices across stains"
---

Aim: To identify structurally similar slices across stains.

Methodology:

Two codes required: 

- Team4Matching.ipynb

- match_pipeline-2.py

[Matching Algorithm Evaluation Tracker](https://docs.google.com/spreadsheets/d/1ftfgVTarxCAADnrV4wQ9Plx2EjlHfv4KF3QgBLAyV2A/edit?gid=1717311473#gid=1717311473)

## Step-by-Step Manual

Follow these steps to use the pipeline to generate matching slices for all patients or a specific subset:

Prepare Image Data: Place .tif image files in the designated folder (e.g., processed_images). Ensure that each patient has images for all three stains (H&E, Melanin, Sox10).

Choose Full or Subset Processing:

For All Patients: Place all images in the same processed_images directory.
For a Subset of Patients: Separate patient image files into their own folders within processed_images (e.g., processed_images/patient1, processed_images/patient2).
Run the Pipeline:

Run match_pipeline.py. A GUI will prompt you to select the directory containing the images.
Open NoahsMatching.ipynb in Jupyter Notebook and execute cells in sequence.
Process and Review Matches:
Upon execution, the pipeline will preprocess, extract contours, and match images, saving results in the matches folder. Images will be organized by patient, with matched slices grouped in subfolders.

## Results

For 1 patient, show all the slices. 
then 
Show images of the matching slices it chose

